"""Post-hoc error listing (Phase 1.5). Reads metrics/per_trace from a fresh evaluation; writes results/phase1_5/errors.md. Post-hoc: nothing here changes any config."""
from __future__ import annotations
import json, sys
from collections import defaultdict
from pathlib import Path
from .heldout.dataset import PATH
from .heldout_eval import run
from .policies import S0, SUITES, selectable_policies, diagnostic_policies
from .detectors import run_all, state_aware
from .detectors.base import as_gens, flat
from .trace import read_jsonl, flat_calls

ROOT = Path(__file__).resolve().parent.parent


def main():
    traces = read_jsonl(PATH); by_id = {t["run_id"]: t for t in traces}
    res = run(traces, ROOT / "results" / "phase1_5")
    L = ["# Every false negative / false positive (held-out v1, SYNTHETIC) - generated by floodlab.phase1_5_errors", "",
         "`at` = intervention call index; `start` = objective loop start; `by` = component that fired first. Explanations are POST-HOC (see PHASE1_5_REPORT.md).", ""]
    for pid in [p.id for p in selectable_policies()] + [p.id for p in diagnostic_policies()]:
        per = res["per_trace"][pid]
        fn = [r for r in per if r["label"] == "flood" and r["intervention"] is None]
        fp = [r for r in per if r["label"] == "legitimate" and r["intervention"] is not None]
        pre = [r for r in per if r["label"] == "flood" and r["intervention"] is not None and r["intervention"] < r["loop_start"]]
        L += [f"## {pid}", f"* false negatives ({len(fn)}): " + (", ".join(r["run_id"] for r in fn) or "none"),
              f"* premature interventions on floods (before loop_start) ({len(pre)}): " + (", ".join(f"{r['run_id']}@{r['intervention']}<{r['loop_start']}" for r in pre) or "none"),
              f"* false positives ({len(fp)}):"]
        for r in fp:
            L.append(f"  * {r['run_id']} [{r['structure']}] at={r['intervention']} of n={r['n_calls']} by={r['by']}")
        L.append("")
    # mechanism data for S0
    L += ["## S0 mechanism data (per trace: detectors that fired, with state suppression counts)", ""]
    rows = []
    for t in traces:
        r = run_all(t, S0); sa = r["state_aware"]
        rows.append((t["run_id"], t["label"], t["ground_truth"]["loop_start_index"], sa.flag, sa.first_index,
                     {k: r[k].first_index for k in ("near_dup", "cycle", "distinct_ratio", "cross_turn") if r[k].flag},
                     sa.evidence.get("suppressed"), sa.evidence.get("earliest")))
    for row in rows:
        if (row[1] == "flood") != row[3]:
            L.append(f"* {row[0]} ({row[1]}) start={row[2]} state_aware={row[3]} at={row[4]} raw_first={row[5]} suppressed={row[6]} earliest={row[7]}")
    (ROOT / "results" / "phase1_5" / "errors.md").write_text("\n".join(L) + "\n")
    print("\n".join(L[:6]), "...", len(L), "lines")


if __name__ == "__main__":
    main()
